name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'

    - name: Change directory to Renthub
      run: cd Rent_Hub

    - name: Install dependencies
      run: |
        cd Rent_Hub
        npm install
    - name: Install dependencies
      run: npm install
      working-directory: rent-hub-fe 

    - name: Build project
      run: |
        cd rent-hub-fe
        npm run build

    - name: Deploy to EC2
      run: |
        cd Rent_Hub
        scp -i /path/to/dev.pem -r ./build/ ubuntu@18.222.21.30:/home/ubuntu/app
        ssh -i /path/to/dev.pem ubuntu@18.222.21.30 'cd /home/ubuntu/app && pm2 restart all || pm2 start npm --name "app" -- start'
      env:
        PRIVATE_KEY: ${{ secrets.EC2_PRIVATE_KEY }}
