name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'

    - name: Change directory to Renthub
      run: cd Rent_Hub

    - name: Install dependencies (Rent Hub)
      run: |
        cd Rent_Hub
        npm install

    - name: Install dependencies (Rent Hub Frontend)
      run: |
        cd rent-hub-fe
        npm install

    - name: Build project
      run: |
        cd rent-hub-fe
        npm run build

    - name: Add host key
      run: |
        ssh-keyscan -H ec2-18-222-21-30.us-east-2.compute.amazonaws.com >> ~/.ssh/known_hosts

    - name: Deploy to EC2
      run: |
        echo "$PRIVATE_KEY" > dev.pem
        chmod 600 dev.pem  # Set proper permissions for the key file
        scp -i dev.pem -r rent-hub-fe/build/ ubuntu@ec2-18-222-21-30.us-east-2.compute.amazonaws.com:/home/ubuntu/app
        ssh -i dev.pem ubuntu@18.222.21.30 << 'EOF'
          cd /home/ubuntu/app
          pm2 restart all || pm2 start npm --name "app" -- start
        EOF
      env:
        PRIVATE_KEY: ${{ secrets.EC2_PRIVATE_KEY }}
